// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student/studentpb/student.proto

package studentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Department           string   `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Course               int32    `protobuf:"varint,5,opt,name=course,proto3" json:"course,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Student) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Student) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Student) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *Student) GetCourse() int32 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *Student) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Student) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateStudentRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentRequest) Reset()         { *m = CreateStudentRequest{} }
func (m *CreateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStudentRequest) ProtoMessage()    {}
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{1}
}

func (m *CreateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentRequest.Unmarshal(m, b)
}
func (m *CreateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentRequest.Marshal(b, m, deterministic)
}
func (m *CreateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentRequest.Merge(m, src)
}
func (m *CreateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStudentRequest.Size(m)
}
func (m *CreateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentRequest proto.InternalMessageInfo

func (m *CreateStudentRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type CreateStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStudentResponse) Reset()         { *m = CreateStudentResponse{} }
func (m *CreateStudentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStudentResponse) ProtoMessage()    {}
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{2}
}

func (m *CreateStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStudentResponse.Unmarshal(m, b)
}
func (m *CreateStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStudentResponse.Marshal(b, m, deterministic)
}
func (m *CreateStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStudentResponse.Merge(m, src)
}
func (m *CreateStudentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStudentResponse.Size(m)
}
func (m *CreateStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStudentResponse proto.InternalMessageInfo

func (m *CreateStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type ReadStudentRequest struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStudentRequest) Reset()         { *m = ReadStudentRequest{} }
func (m *ReadStudentRequest) String() string { return proto.CompactTextString(m) }
func (*ReadStudentRequest) ProtoMessage()    {}
func (*ReadStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{3}
}

func (m *ReadStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStudentRequest.Unmarshal(m, b)
}
func (m *ReadStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStudentRequest.Marshal(b, m, deterministic)
}
func (m *ReadStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStudentRequest.Merge(m, src)
}
func (m *ReadStudentRequest) XXX_Size() int {
	return xxx_messageInfo_ReadStudentRequest.Size(m)
}
func (m *ReadStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStudentRequest proto.InternalMessageInfo

func (m *ReadStudentRequest) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

type ReadStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStudentResponse) Reset()         { *m = ReadStudentResponse{} }
func (m *ReadStudentResponse) String() string { return proto.CompactTextString(m) }
func (*ReadStudentResponse) ProtoMessage()    {}
func (*ReadStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{4}
}

func (m *ReadStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStudentResponse.Unmarshal(m, b)
}
func (m *ReadStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStudentResponse.Marshal(b, m, deterministic)
}
func (m *ReadStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStudentResponse.Merge(m, src)
}
func (m *ReadStudentResponse) XXX_Size() int {
	return xxx_messageInfo_ReadStudentResponse.Size(m)
}
func (m *ReadStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStudentResponse proto.InternalMessageInfo

func (m *ReadStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type UpdateStudentRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStudentRequest) Reset()         { *m = UpdateStudentRequest{} }
func (m *UpdateStudentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStudentRequest) ProtoMessage()    {}
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{5}
}

func (m *UpdateStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStudentRequest.Unmarshal(m, b)
}
func (m *UpdateStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStudentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStudentRequest.Merge(m, src)
}
func (m *UpdateStudentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStudentRequest.Size(m)
}
func (m *UpdateStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStudentRequest proto.InternalMessageInfo

func (m *UpdateStudentRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type UpdateStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStudentResponse) Reset()         { *m = UpdateStudentResponse{} }
func (m *UpdateStudentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStudentResponse) ProtoMessage()    {}
func (*UpdateStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{6}
}

func (m *UpdateStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStudentResponse.Unmarshal(m, b)
}
func (m *UpdateStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStudentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStudentResponse.Merge(m, src)
}
func (m *UpdateStudentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStudentResponse.Size(m)
}
func (m *UpdateStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStudentResponse proto.InternalMessageInfo

func (m *UpdateStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type DeleteStudentRequest struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStudentRequest) Reset()         { *m = DeleteStudentRequest{} }
func (m *DeleteStudentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStudentRequest) ProtoMessage()    {}
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{7}
}

func (m *DeleteStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStudentRequest.Unmarshal(m, b)
}
func (m *DeleteStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStudentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStudentRequest.Merge(m, src)
}
func (m *DeleteStudentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStudentRequest.Size(m)
}
func (m *DeleteStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStudentRequest proto.InternalMessageInfo

func (m *DeleteStudentRequest) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

type DeleteStudentResponse struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStudentResponse) Reset()         { *m = DeleteStudentResponse{} }
func (m *DeleteStudentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStudentResponse) ProtoMessage()    {}
func (*DeleteStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{8}
}

func (m *DeleteStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStudentResponse.Unmarshal(m, b)
}
func (m *DeleteStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStudentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStudentResponse.Merge(m, src)
}
func (m *DeleteStudentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStudentResponse.Size(m)
}
func (m *DeleteStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStudentResponse proto.InternalMessageInfo

func (m *DeleteStudentResponse) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

type ListStudentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStudentRequest) Reset()         { *m = ListStudentRequest{} }
func (m *ListStudentRequest) String() string { return proto.CompactTextString(m) }
func (*ListStudentRequest) ProtoMessage()    {}
func (*ListStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{9}
}

func (m *ListStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStudentRequest.Unmarshal(m, b)
}
func (m *ListStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStudentRequest.Marshal(b, m, deterministic)
}
func (m *ListStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStudentRequest.Merge(m, src)
}
func (m *ListStudentRequest) XXX_Size() int {
	return xxx_messageInfo_ListStudentRequest.Size(m)
}
func (m *ListStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStudentRequest proto.InternalMessageInfo

type ListStudentResponse struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStudentResponse) Reset()         { *m = ListStudentResponse{} }
func (m *ListStudentResponse) String() string { return proto.CompactTextString(m) }
func (*ListStudentResponse) ProtoMessage()    {}
func (*ListStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{10}
}

func (m *ListStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStudentResponse.Unmarshal(m, b)
}
func (m *ListStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStudentResponse.Marshal(b, m, deterministic)
}
func (m *ListStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStudentResponse.Merge(m, src)
}
func (m *ListStudentResponse) XXX_Size() int {
	return xxx_messageInfo_ListStudentResponse.Size(m)
}
func (m *ListStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStudentResponse proto.InternalMessageInfo

func (m *ListStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "student.Student")
	proto.RegisterType((*CreateStudentRequest)(nil), "student.CreateStudentRequest")
	proto.RegisterType((*CreateStudentResponse)(nil), "student.CreateStudentResponse")
	proto.RegisterType((*ReadStudentRequest)(nil), "student.ReadStudentRequest")
	proto.RegisterType((*ReadStudentResponse)(nil), "student.ReadStudentResponse")
	proto.RegisterType((*UpdateStudentRequest)(nil), "student.UpdateStudentRequest")
	proto.RegisterType((*UpdateStudentResponse)(nil), "student.UpdateStudentResponse")
	proto.RegisterType((*DeleteStudentRequest)(nil), "student.DeleteStudentRequest")
	proto.RegisterType((*DeleteStudentResponse)(nil), "student.DeleteStudentResponse")
	proto.RegisterType((*ListStudentRequest)(nil), "student.ListStudentRequest")
	proto.RegisterType((*ListStudentResponse)(nil), "student.ListStudentResponse")
}

func init() { proto.RegisterFile("student/studentpb/student.proto", fileDescriptor_6e507e88556d669a) }

var fileDescriptor_6e507e88556d669a = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x95, 0xa1, 0xe0, 0x7a, 0x2c, 0x50, 0xb5, 0x35, 0x95, 0x05, 0x85, 0x22, 0x4e, 0xa8, 0x07,
	0x5a, 0x81, 0xda, 0x7b, 0x20, 0x87, 0x24, 0x8a, 0x7c, 0x30, 0xca, 0x25, 0x17, 0xb4, 0xb0, 0x13,
	0xc9, 0x12, 0xfe, 0x88, 0x77, 0xc9, 0x4f, 0xc9, 0xbf, 0xc9, 0x7f, 0x8b, 0x58, 0xd6, 0xd6, 0xda,
	0x38, 0x42, 0x90, 0x93, 0x3d, 0x6f, 0x76, 0x66, 0xe7, 0xbd, 0x37, 0x5a, 0xf8, 0xc5, 0xc5, 0x8e,
	0x61, 0x24, 0xfe, 0xa8, 0x6f, 0xb2, 0xce, 0xfe, 0x26, 0x49, 0x1a, 0x8b, 0x98, 0x98, 0x2a, 0x1c,
	0xbd, 0x19, 0x60, 0x2e, 0x0f, 0xff, 0xa4, 0x0d, 0xb5, 0x80, 0xb9, 0xc6, 0xd0, 0x18, 0x5b, 0x7e,
	0x2d, 0x60, 0xa4, 0x0f, 0xf0, 0x14, 0xa4, 0x5c, 0xac, 0x22, 0x1a, 0xa2, 0x5b, 0x93, 0xb8, 0x25,
	0x11, 0x8f, 0x86, 0x48, 0x7a, 0x60, 0x6d, 0x69, 0x96, 0xad, 0xcb, 0xec, 0xd7, 0x3d, 0x20, 0x93,
	0x03, 0x00, 0x86, 0x09, 0x4d, 0x45, 0x88, 0x91, 0x70, 0xbf, 0xc8, 0xac, 0x86, 0x90, 0x1f, 0xd0,
	0xdc, 0xc4, 0xbb, 0x94, 0xa3, 0xdb, 0x18, 0x1a, 0xe3, 0x86, 0xaf, 0x22, 0xe2, 0x82, 0x49, 0x19,
	0x4b, 0x91, 0x73, 0xb7, 0x29, 0x8b, 0xb2, 0x90, 0x38, 0xd0, 0xc0, 0x90, 0x06, 0x5b, 0xd7, 0x94,
	0xf8, 0x21, 0x18, 0xcd, 0xc1, 0x59, 0xa4, 0x48, 0x05, 0x2a, 0x12, 0x3e, 0x3e, 0xef, 0x90, 0x0b,
	0xf2, 0x1b, 0x32, 0x8a, 0x92, 0x90, 0x3d, 0xfd, 0x36, 0xc9, 0x14, 0xc8, 0x4e, 0xe6, 0x1a, 0x2c,
	0xa0, 0x53, 0xea, 0xc1, 0x93, 0x38, 0xe2, 0x78, 0x56, 0x93, 0x19, 0x10, 0x1f, 0x29, 0x2b, 0x8d,
	0xd1, 0x07, 0x50, 0x07, 0x56, 0xb9, 0xb4, 0x96, 0x42, 0x6e, 0xd9, 0xe8, 0x0a, 0xbe, 0x17, 0x8a,
	0x2e, 0xb8, 0x77, 0x0e, 0xce, 0x43, 0xc2, 0x3e, 0x2d, 0x40, 0xa9, 0xc7, 0x05, 0x83, 0xfc, 0x03,
	0xe7, 0x1a, 0xb7, 0x78, 0x34, 0xc8, 0x09, 0x09, 0xfe, 0x43, 0xa7, 0x54, 0xa6, 0xee, 0x3e, 0x51,
	0xe7, 0x00, 0xb9, 0x0f, 0xb8, 0x28, 0x5e, 0xb6, 0x17, 0xb4, 0x80, 0x9e, 0xcf, 0x63, 0xfa, 0x5a,
	0x87, 0xb6, 0x02, 0x97, 0x98, 0xbe, 0x04, 0x1b, 0x24, 0x1e, 0xb4, 0x0a, 0x0b, 0x42, 0xfa, 0x79,
	0x79, 0xd5, 0xf2, 0x75, 0x07, 0x1f, 0xa5, 0xd5, 0x38, 0x37, 0x60, 0x6b, 0xb6, 0x93, 0x5e, 0x7e,
	0xfc, 0x78, 0x83, 0xba, 0x3f, 0xab, 0x93, 0xaa, 0x93, 0x07, 0xad, 0x82, 0x73, 0xda, 0x64, 0x55,
	0x5b, 0xa1, 0x4d, 0x56, 0x6d, 0xb8, 0x07, 0xad, 0x82, 0x1b, 0x5a, 0xbf, 0x2a, 0x73, 0xb5, 0x7e,
	0xd5, 0x26, 0xde, 0x81, 0xad, 0xf9, 0xa1, 0x31, 0x3d, 0xf6, 0x4e, 0x63, 0x5a, 0x61, 0xe1, 0x5f,
	0x63, 0x6e, 0x3f, 0x5a, 0xf9, 0x73, 0xb6, 0x6e, 0xca, 0x77, 0x6c, 0xf6, 0x1e, 0x00, 0x00, 0xff,
	0xff, 0xfa, 0xd1, 0x4e, 0x1c, 0xea, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error)
	ReadStudent(ctx context.Context, in *ReadStudentRequest, opts ...grpc.CallOption) (*ReadStudentResponse, error)
	UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*UpdateStudentResponse, error)
	DeleteStudent(ctx context.Context, in *DeleteStudentRequest, opts ...grpc.CallOption) (*DeleteStudentResponse, error)
	ListStudent(ctx context.Context, in *ListStudentRequest, opts ...grpc.CallOption) (StudentService_ListStudentClient, error)
}

type studentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStudentServiceClient(cc *grpc.ClientConn) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) CreateStudent(ctx context.Context, in *CreateStudentRequest, opts ...grpc.CallOption) (*CreateStudentResponse, error) {
	out := new(CreateStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) ReadStudent(ctx context.Context, in *ReadStudentRequest, opts ...grpc.CallOption) (*ReadStudentResponse, error) {
	out := new(ReadStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/ReadStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) UpdateStudent(ctx context.Context, in *UpdateStudentRequest, opts ...grpc.CallOption) (*UpdateStudentResponse, error) {
	out := new(UpdateStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/UpdateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) DeleteStudent(ctx context.Context, in *DeleteStudentRequest, opts ...grpc.CallOption) (*DeleteStudentResponse, error) {
	out := new(DeleteStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/DeleteStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) ListStudent(ctx context.Context, in *ListStudentRequest, opts ...grpc.CallOption) (StudentService_ListStudentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StudentService_serviceDesc.Streams[0], "/student.StudentService/ListStudent", opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceListStudentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StudentService_ListStudentClient interface {
	Recv() (*ListStudentResponse, error)
	grpc.ClientStream
}

type studentServiceListStudentClient struct {
	grpc.ClientStream
}

func (x *studentServiceListStudentClient) Recv() (*ListStudentResponse, error) {
	m := new(ListStudentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	CreateStudent(context.Context, *CreateStudentRequest) (*CreateStudentResponse, error)
	ReadStudent(context.Context, *ReadStudentRequest) (*ReadStudentResponse, error)
	UpdateStudent(context.Context, *UpdateStudentRequest) (*UpdateStudentResponse, error)
	DeleteStudent(context.Context, *DeleteStudentRequest) (*DeleteStudentResponse, error)
	ListStudent(*ListStudentRequest, StudentService_ListStudentServer) error
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) CreateStudent(ctx context.Context, req *CreateStudentRequest) (*CreateStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudent not implemented")
}
func (*UnimplementedStudentServiceServer) ReadStudent(ctx context.Context, req *ReadStudentRequest) (*ReadStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStudent not implemented")
}
func (*UnimplementedStudentServiceServer) UpdateStudent(ctx context.Context, req *UpdateStudentRequest) (*UpdateStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudent not implemented")
}
func (*UnimplementedStudentServiceServer) DeleteStudent(ctx context.Context, req *DeleteStudentRequest) (*DeleteStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudent not implemented")
}
func (*UnimplementedStudentServiceServer) ListStudent(req *ListStudentRequest, srv StudentService_ListStudentServer) error {
	return status.Errorf(codes.Unimplemented, "method ListStudent not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CreateStudent(ctx, req.(*CreateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_ReadStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).ReadStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/ReadStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).ReadStudent(ctx, req.(*ReadStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_UpdateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).UpdateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/UpdateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).UpdateStudent(ctx, req.(*UpdateStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_DeleteStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).DeleteStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/DeleteStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).DeleteStudent(ctx, req.(*DeleteStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_ListStudent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListStudentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StudentServiceServer).ListStudent(m, &studentServiceListStudentServer{stream})
}

type StudentService_ListStudentServer interface {
	Send(*ListStudentResponse) error
	grpc.ServerStream
}

type studentServiceListStudentServer struct {
	grpc.ServerStream
}

func (x *studentServiceListStudentServer) Send(m *ListStudentResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "student.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _StudentService_CreateStudent_Handler,
		},
		{
			MethodName: "ReadStudent",
			Handler:    _StudentService_ReadStudent_Handler,
		},
		{
			MethodName: "UpdateStudent",
			Handler:    _StudentService_UpdateStudent_Handler,
		},
		{
			MethodName: "DeleteStudent",
			Handler:    _StudentService_DeleteStudent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStudent",
			Handler:       _StudentService_ListStudent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "student/studentpb/student.proto",
}
